import asyncio
import httpx
import time
from pathlib import Path
from core.config import settings

async def fetch_source(client: httpx.AsyncClient, source_url: str) -> set[str]:
    """Tải một nguồn danh sách đen duy nhất một cách bất đồng bộ."""
    domains = set()
    try:
        response = await client.get(source_url, timeout=30.0, follow_redirects=True)
        response.raise_for_status() 
        
        for line in response.text.splitlines():
            line = line.strip()
            if line and not line.startswith('#'):
                parts = line.split()
                domain = parts[-1]
                if domain not in ("0.0.0.0", "127.0.0.1", "localhost", "localhost.localdomain"):
                    domains.add(domain)
        print(f"Đã tải thành công {len(domains)} tên miền từ {source_url}")
        return domains
    except httpx.RequestError as e:
        print(f"Lỗi khi tải {source_url}: {e}")
        return domains

async def start_blacklist_updater(manager):
    """
    Tác vụ nền chạy vĩnh viễn, cập nhật danh sách đen 
    và kích hoạt hot-reload.
    """
    await asyncio.sleep(10) # Chờ một chút sau khi khởi động
    
    while True:
        print("[Updater] Bắt đầu tác vụ cập nhật danh sách đen...")
        combined_blacklist = set()
        
        async with httpx.AsyncClient() as client:
            tasks = tasks = [fetch_source(client, url) for url in settings.BLACKLIST_SOURCES]
            # Chạy tất cả các bản tải xuống đồng thời
            results = await asyncio.gather(*tasks)
            
            for domain_set in results:
                combined_blacklist.update(domain_set)
        
        if combined_blacklist:
            try:
                filepath = Path(settings.BLACKLIST_PATH)
                filepath.parent.mkdir(parents=True, exist_ok=True)
                
                with open(filepath, 'w') as f:
                    f.write(f"# blacklist generated by nt140-firewall updater\n")
                    f.write(f"# generated: {time.asctime()}Z\n")
                    f.write(f"# sources: {len(settings.BLACKLIST_SOURCES)}\n\n")
                    # Ghi danh sách đã sắp xếp
                    for domain in sorted(list(combined_blacklist)):
                        f.write(f"{domain}\n")
                
                print(f"[Updater] Đã ghi {len(combined_blacklist)} tên miền vào {filepath}")
                
                # Kích hoạt hot-reload trong trình quản lý bộ lọc
                await manager.reload_blacklist()
                
            except Exception as e:
                print(f"[Updater] Lỗi khi ghi danh sách đen mới: {e}")
        
        # Chờ đến lần chạy tiếp theo
        await asyncio.sleep(settings.BLACKLIST_REFRESH_INTERVAL)